version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./django_app:/app
      - ./.env:/app/.env:ro

volumes:
  pgdata:
