# Generated by Django 5.2.1 on 2025-09-13 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='audio')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=255)),
                ('is_first', models.BooleanField(default=False)),
                ('is_second', models.BooleanField(default=False)),
                ('is_last', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='pdf')),
                ('is_first', models.BooleanField(default=False)),
                ('is_second', models.BooleanField(default=False)),
                ('is_last', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=255)),
                ('paid', models.BooleanField(default=False)),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Уникальный идентификатор чата в Telegram', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('additional_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_as_additional_audio', related_query_name='exercise_as_additional_audio', to='CoachAsistant.audio')),
                ('end_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_as_end_audio', related_query_name='exercise_as_end_audio', to='CoachAsistant.audio')),
                ('start_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_as_start_audio', related_query_name='exercise_as_start_audio', to='CoachAsistant.audio')),
                ('additional_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_as_additional_pdf', related_query_name='exercise_as_additional_pdf', to='CoachAsistant.pdffile')),
                ('end_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_as_end_pdf', related_query_name='exercise_as_end_pdf', to='CoachAsistant.pdffile')),
                ('start_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_as_start_pdf', related_query_name='exercise_as_start_pdf', to='CoachAsistant.pdffile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('ended', 'Ended'), ('done', 'Done')], default='not_started')),
                ('current_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_current', to='CoachAsistant.exercise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='CoachAsistant.user')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_instruction')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('user', 'User'), ('assistant', 'Assistant'), ('internal', 'Внутренняя')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('audio', 'Audio'), ('pdf', 'PDF'), ('text', 'Text')], default='text', max_length=50)),
                ('audio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoachAsistant.audio')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CoachAsistant.chat')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CoachAsistant.exercise')),
                ('pdf', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoachAsistant.pdffile')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('ended', 'Ended'), ('done', 'Done')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='CoachAsistant.chat')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='CoachAsistant.exercise')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='CoachAsistant.user')),
            ],
            options={
                'indexes': [models.Index(fields=['chat', 'status'], name='CoachAsista_chat_id_f3f5de_idx'), models.Index(fields=['exercise', 'status'], name='CoachAsista_exercis_cd0126_idx')],
                'unique_together': {('chat', 'exercise')},
            },
        ),
    ]
