# Generated by Django 5.2.1 on 2025-07-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachAsistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('user', 'User')], max_length=50)),
                ('content', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CoachAsistant.chat')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.BigIntegerField(help_text='Уникальный идентификатор чата в Telegram', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Заголовок чата (может быть пустым для личного диалога)', max_length=255, null=True)),
                ('username', models.CharField(blank=True, help_text='Username пользователя (если есть)', max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя', max_length=255, null=True)),
                ('paid', models.BooleanField(default=False, help_text='Статус оплаты (True, если оплачено)')),
                ('assistant', models.ForeignKey(blank=True, help_text='Ассистент, связанный с этим Telegram-пользователем', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='CoachAsistant.openaiassistant')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='CoachAsistant.openaithread')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='CoachAsistant.user'),
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
