# Generated by Django 5.2.1 on 2025-07-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachAsistant', '0002_chat_exercise_message_user_chat_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='exercise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('user', 'User'), ('assistant', 'Assistant')], max_length=50),
        ),
    ]
