# Generated by Django 5.2.1 on 2025-07-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachAsistant', '0003_chat_exercise_alter_message_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Aactive'), ('inactive', 'Inactive')], default='active', max_length=50)),
            ],
        ),
    ]
